# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

server:
  port: 5656

security.auth.enabled: false
security.basic.enable: false
security.ignored: /**

simulation:
  grid: 50
  drivers: 2500
  passengers: 10

kafka:
  topic:
    from-driver: from-driver
    to-driver: to-driver
    from-passenger: from-passenger
    to-passenger: to-passenger
  listeners:
    transactions.id: simulator-java-listener
  bootstrap-servers: kafka-broker:9092

web-socket:
  topic:
    passenger: /topic/passenger
    driver: /topic/driver

management.endpoints.web.exposure.include: mappings, loggers
  
